# Generated by Django 2.0.2 on 2018-03-05 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now_add=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('what', models.CharField(choices=[('BTC', 'BTC'), ('LTC', 'LTC')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Amount')),
                ('amount_completed', models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Amount completed')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Buy or sell at price')),
                ('trade_currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')], max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('done', 'Done')], default='ACTIVE', max_length=6)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_order_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_order_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
